// seeds/001_marketplaces.js
exports.seed = async function (knex) {
  await knex('marketplaces').del();

  await knex('marketplaces').insert([
    {
      id: 'ebay',
      name: 'eBay',
      logo_url: '/images/marketplaces/ebay.svg',
      integration_type: 'api',
      active: true,
      supported_categories: JSON.stringify(['clothing', 'shoes', 'accessories', 'electronics', 'home', 'collectibles']),
      fee_structure: JSON.stringify({ base_rate: 0.1312, insertion_fee: 0, payment_processing: 0.0299 }),
      listing_requirements: JSON.stringify({ max_title_length: 80, min_images: 1, max_images: 24 }),
      rate_limit_per_minute: 40,
    },
    {
      id: 'poshmark',
      name: 'Poshmark',
      logo_url: '/images/marketplaces/poshmark.svg',
      integration_type: 'automation',
      active: true,
      supported_categories: JSON.stringify(['clothing', 'shoes', 'accessories', 'home', 'beauty']),
      fee_structure: JSON.stringify({ flat_rate: 0.20, under_15: 2.95 }),
      listing_requirements: JSON.stringify({ max_title_length: 80, min_images: 1, max_images: 16 }),
      rate_limit_per_minute: 10,
    },
    {
      id: 'mercari',
      name: 'Mercari',
      logo_url: '/images/marketplaces/mercari.svg',
      integration_type: 'automation',
      active: true,
      supported_categories: JSON.stringify(['clothing', 'shoes', 'electronics', 'toys', 'home', 'beauty']),
      fee_structure: JSON.stringify({ base_rate: 0.10 }),
      listing_requirements: JSON.stringify({ max_title_length: 80, min_images: 1, max_images: 12 }),
      rate_limit_per_minute: 10,
    },
    {
      id: 'depop',
      name: 'Depop',
      logo_url: '/images/marketplaces/depop.svg',
      integration_type: 'automation',
      active: true,
      supported_categories: JSON.stringify(['clothing', 'shoes', 'accessories', 'vintage']),
      fee_structure: JSON.stringify({ base_rate: 0.10 }),
      listing_requirements: JSON.stringify({ max_title_length: 280, min_images: 1, max_images: 4 }),
      rate_limit_per_minute: 10,
    },
    {
      id: 'facebook',
      name: 'Facebook Marketplace',
      logo_url: '/images/marketplaces/facebook.svg',
      integration_type: 'hybrid',
      active: true,
      supported_categories: JSON.stringify(['clothing', 'electronics', 'furniture', 'vehicles', 'home']),
      fee_structure: JSON.stringify({ base_rate: 0.05 }),
      listing_requirements: JSON.stringify({ max_title_length: 100, min_images: 1, max_images: 10 }),
      rate_limit_per_minute: 20,
    },
    {
      id: 'grailed',
      name: 'Grailed',
      logo_url: '/images/marketplaces/grailed.svg',
      integration_type: 'automation',
      active: true,
      supported_categories: JSON.stringify(['menswear', 'streetwear', 'designer']),
      fee_structure: JSON.stringify({ base_rate: 0.09, payment_processing: 0.0299 }),
      listing_requirements: JSON.stringify({ max_title_length: 100, min_images: 1, max_images: 20 }),
      rate_limit_per_minute: 10,
    },
    {
      id: 'kidizen',
      name: 'Kidizen',
      logo_url: '/images/marketplaces/kidizen.svg',
      integration_type: 'automation',
      active: false,
      supported_categories: JSON.stringify(['kids_clothing', 'kids_shoes', 'toys', 'baby']),
      fee_structure: JSON.stringify({ base_rate: 0.12 }),
      listing_requirements: JSON.stringify({ max_title_length: 80, min_images: 1, max_images: 8 }),
      rate_limit_per_minute: 10,
    },
    {
      id: 'vestiaire',
      name: 'Vestiaire Collective',
      logo_url: '/images/marketplaces/vestiaire.svg',
      integration_type: 'automation',
      active: false,
      supported_categories: JSON.stringify(['luxury', 'designer', 'clothing', 'bags', 'shoes']),
      fee_structure: JSON.stringify({ base_rate: 0.15 }),
      listing_requirements: JSON.stringify({ max_title_length: 100, min_images: 2, max_images: 10 }),
      rate_limit_per_minute: 10,
    },
  ]);
};
